# Generated by Django 5.0.3 on 2024-04-30 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("page", "0012_rename_bannerimage_patreonpage_banner_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatreonDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("Amount_added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pagemodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_3",
                        to="page.patreonpage",
                    ),
                ),
                (
                    "pageuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
