# Generated by Django 5.0.3 on 2024-05-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("page", "0012_rename_bannerimage_patreonpage_banner_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatreonSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateOpened", models.DateTimeField(auto_now_add=True)),
                ("dateClosed", models.DateTimeField(null=True)),
                (
                    "pagesub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_5",
                        to="page.patreonpage",
                    ),
                ),
                (
                    "subuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_4",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
