# Generated by Django 5.0.3 on 2024-04-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreonpage',
            name='donatedBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patreonpage',
            name='donation',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
