# Generated by Django 5.0.3 on 2024-04-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_patreonpage_donatedby_patreonpage_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreonpage',
            name='donation',
        ),
    ]
