# Generated by Django 5.0.3 on 2024-04-14 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_patreonpage_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patreonpage',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patreonpage',
            name='donatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
