# Generated by Django 5.0.3 on 2024-04-14 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_patreonpage_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreonpage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
