# Generated by Django 5.0.3 on 2024-04-15 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_patreonpage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreonpage',
            name='donatedBy',
        ),
        migrations.AlterField(
            model_name='patreonpage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/page'),
        ),
        migrations.AddField(
            model_name='patreonpage',
            name='donatedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
