# Generated by Django 5.0.3 on 2024-04-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_remove_patreonpage_donatedby_alter_patreonpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreonpage',
            name='donatedBy',
        ),
    ]
