# Generated by Django 5.0.3 on 2024-04-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0007_remove_patreonpage_donatedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patreonpage",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="patreonpage",
            name="goal_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="patreonpage",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
