# Generated by Django 5.0.3 on 2024-04-29 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_title'),
        ('page', '0010_patreonpage_subscriber_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreonpage',
            name='image',
        ),
        migrations.AddField(
            model_name='patreonpage',
            name='bannerImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
        migrations.AlterField(
            model_name='patreonpage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patreonpage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
