# Generated by Django 5.0.3 on 2024-04-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_patreonpage_image_patreonpage_bannerimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patreonpage',
            old_name='bannerImage',
            new_name='banner_image',
        ),
    ]
