# Generated by Django 5.0.3 on 2024-05-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_rename_bannerimage_patreonpage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreonpage',
            name='current_amount',
        ),
    ]
