# Generated by Django 5.0.3 on 2024-05-02 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_image_file'),
        ('page', '0013_remove_patreonpage_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patreonpage',
            name='banner_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
