# Generated by Django 5.0.3 on 2024-04-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
