# Generated by Django 5.0.3 on 2024-04-11 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0004_alter_patreonuser_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patreonuser",
            old_name="id",
            new_name="userid",
        ),
    ]
