# Generated by Django 5.0.3 on 2024-04-29 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_title'),
        ('registration', '0005_rename_id_patreonuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreonuser',
            name='profileImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
