# Generated by Django 5.0.3 on 2024-04-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_patreonuser_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patreonuser',
            old_name='profileImage',
            new_name='profile_image',
        ),
    ]
