# Generated by Django 5.0.3 on 2024-04-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload_profile_image", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
        migrations.AddField(
            model_name="image",
            name="image_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="image",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
